name:                hamming-distance
version:             0.1.0.0
github:              "PascalVaudrevange/hamming-distance"
license:             BSD3
author:              "Pascal Vaudrevange"
maintainer:          "pascal@vaudrevange.com"
copyright:           "2020 Pascal Vaudrevange"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/PascalVaudrevange/hamming-distance#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- utf8-string
- extra
- string-random
- random
- text-conversions

library:
  source-dirs: src

executables:
  hamming-distance-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hamming-distance

tests:
  hamming-distance-test:
    main:                TestHammingDistance.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hamming-distance
    - HUnit
